/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package App;

import java.sql.*;
import br.com.infox.dal.ModuloConexao;
import javax.swing.JOptionPane;

/**
 *
 * @author Leandro
 */
public class TelaCadastroUsuarioSeminario extends javax.swing.JFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form TelaCadastroUsuarioSeminario2
     */
    public TelaCadastroUsuarioSeminario() {
        initComponents();
        setLocationRelativeTo(null);
        conexao = ModuloConexao.conector();
    }

    private void cadastrar() {
        String sql = "insert into tbusuario(nome,senha,gennasc,geniden,email) values(?,?,?,?,?)";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, jtNome.getText());
            pst.setString(5, jtEmail.getText());
            pst.setString(2, jpSenha.getText());
            pst.setString(3, jcGeneroNasc.getSelectedItem().toString());
            pst.setString(4, jcGeneroIden.getSelectedItem().toString());
            //valid~ção dos campos obrigatorios

            String gnasc = jcGeneroNasc.getSelectedItem().toString();
            String giden = jcGeneroIden.getSelectedItem().toString();

            if ((gnasc.equals("Homem")) && giden.equals("Masculino")) {
                JOptionPane.showMessageDialog(null, "Apenas pessoas que se indentificam com mulheres podem se cadastrar");
            } else {

                if ((((jtNome.getText().isEmpty()) || (jtEmail.getText().isEmpty()) || jpSenha.getText().isEmpty()))) {
                    JOptionPane.showMessageDialog(null, "Campos obrigatorios devem ser preenchidos");
                } else {

                    //a linha abaixo adiciona os dados do formulario na tabela de usuario
                    int adicionado = pst.executeUpdate();
                    System.out.println(adicionado);
                    if (adicionado > 0) {
                        JOptionPane.showMessageDialog(null, "Novo usuario criado com sucesso");
                        jtNome.setText(null);
                        jtEmail.setText(null);
                        jpSenha.setText(null);
                        jcGeneroNasc.setSelectedItem(null);
                        jcGeneroIden.setSelectedItem(null);

                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jtEmail = new javax.swing.JTextField();
        jpSenha = new javax.swing.JPasswordField();
        jcGeneroNasc = new javax.swing.JComboBox<>();
        jcGeneroIden = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Women's Academy - Cadastro");
        setMinimumSize(new java.awt.Dimension(764, 470));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 60, 36, 16);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 110, 32, 16);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Sexo Biologico:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(310, 60, 90, 16);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Genêro:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(310, 110, 60, 16);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Senha:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 160, 35, 16);

        jtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(jtNome);
        jtNome.setBounds(50, 80, 180, 22);

        jtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(jtEmail);
        jtEmail.setBounds(50, 130, 180, 22);
        getContentPane().add(jpSenha);
        jpSenha.setBounds(50, 180, 180, 22);

        jcGeneroNasc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Mulher", "Homem" }));
        jcGeneroNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcGeneroNascActionPerformed(evt);
            }
        });
        getContentPane().add(jcGeneroNasc);
        jcGeneroNasc.setBounds(310, 80, 190, 22);

        jcGeneroIden.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Feminino", "Masculino", "Não Binario" }));
        getContentPane().add(jcGeneroIden);
        jcGeneroIden.setBounds(310, 130, 190, 22);

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(370, 230, 120, 30);

        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(240, 230, 110, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cadastro");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 20, 120, 33);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Imagens Mulheres Seminario Login 2.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 770, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcGeneroNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcGeneroNascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcGeneroNascActionPerformed

    private void jtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNomeActionPerformed

    private void jtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtEmailActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cadastrar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        TeladeLoginSeminario login = new TeladeLoginSeminario();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuarioSeminario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuarioSeminario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuarioSeminario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuarioSeminario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroUsuarioSeminario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> jcGeneroIden;
    private javax.swing.JComboBox<String> jcGeneroNasc;
    private javax.swing.JPasswordField jpSenha;
    private javax.swing.JTextField jtEmail;
    private javax.swing.JTextField jtNome;
    // End of variables declaration//GEN-END:variables
}
